version: '2.1'

services:
  node1.testnet.geodb.com:
    container_name: node1.testnet.geodb.com
    image: ethereum/client-go:alltools-stable
    working_dir: /
    restart: always
    command: >
      /bin/sh -c
      "
      . /commands/get-boot-node-info.sh & 
      . /commands/start.sh;
      "
    volumes:
      - ./credentials:/credentials
      - ./datadir:/datadir
      - ./genesis:/genesis
      - ./commands:/commands
      - ./boot-node-info:/boot-node-info
    ports:
      - 30303:30303
    healthcheck:
      test: ['CMD', 'cat', '/boot-node-info/enr']
      interval: 5s
      timeout: 1s
      retries: 20

  node2.testnet.geodb.com:
    container_name: node2.testnet.geodb.com
    image: ethereum/client-go:alltools-stable
    working_dir: /
    restart: always
    command: >
      /bin/sh -c
      "
      . /commands/attach-peer.sh
      "
    depends_on:
      node1.testnet.geodb.com:
        condition: service_healthy
    volumes:
      - ./boot-node-info:/boot-node-info
      - ./genesis:/genesis
      - ./commands:/commands
      - ./light-node-datadir:/datadir
    ports:
      - 7545:7545
