version: '2.1'

services:
  poa-master-node:
    container_name: poa-master-node
    image: ethereum/client-go:alltools-stable
    working_dir: /
    restart: always
    command: >
      /bin/sh -c
      "
      . /commands/get-boot-node-info.sh & 
      . /commands/start.sh;
      "
    volumes:
      - ./credentials:/credentials
      - ./datadir:/datadir
      - ./genesis:/genesis
      - ./commands:/commands
      - ./boot-node-info:/boot-node-info
    networks:
      poa:
        ipv4_address: 172.0.254.128
    ports:
      - 30303:30303
    healthcheck:
      test: 'cat /boot-node-info/enode && cat /boot-node-info/network'
      interval: 5s
      timeout: 1s
      retries: 20

  poa-member-node:
    container_name: poa-member-node
    image: ethereum/client-go:alltools-stable
    working_dir: /
    restart: always
    command: >
      /bin/sh -c
      "
      . /commands/keep-alive.sh & 
      . /commands/attach-peer.sh
      "
    depends_on:
      poa-master-node:
        condition: service_healthy
    volumes:
      - ./boot-node-info:/boot-node-info
      - ./genesis:/genesis
      - ./commands:/commands
      - ./datadir:/bootstrap
      - ./member-node-datadir:/datadir
    networks:
      poa:
        ipv4_address: 172.0.254.129
    ports:
      - 7545:7545
      - 7546:7546
    ipc: host

networks:
  poa:
    ipam:
      driver: default
      config:
        - subnet: 172.0.254.0/24
